### ISSUE TITLE
Error: L should not contain any digits

### ISSUE THREAD

**Issue by SaeidBayat** [danielrherber/pm-suspensions#1]
I receive the following error when I run the example:

 "L should not contain any digits"

The error occurs in the "PMA_DefaultNSC" function. I commented out the lines that print this error, but it generated more errors. The issue did not resolve even after installing Matlab 2018a.

**Comment by danielrherber** [comment]
Hi Saeid. This issue is related to an update in [pm-architectures-project](https://github.com/danielrherber/pm-architectures-project) dependency.

I would first try this version [link](https://github.com/danielrherber/pm-architectures-project/commit/633f77835654bc802ae790a6761541eb0bc0c099), which was made available on Dec 10, 2017. This was the commit that introduced that error message on Jan 5, 2018: [link](https://github.com/danielrherber/pm-architectures-project/commit/6d57b60a7d10e6774579fd9c9a6011deb74b06b2#diff-7de8d16fa017004cfb4333ae75a1a405237b1b6fe3ffe3f6ec0d27be56095b0b).

If that doesn't work, then I can do some digging to either 1) see which version I used originally for this work or 2) update the code to support the latest version. There are significant improvements to the graph enumeration algorithms since then (see [link](https://www.engr.colostate.edu/%7Edrherber/files/Herber2020b.pdf)) in [v4.0](https://github.com/danielrherber/pm-architectures-project/releases/tag/v4.0), so it would be good to get it working on here.

**Comment by SaeidBayat** [comment]
Sorry for the delayed response. I tried the other version but it did not resolve the issue.

**Comment by SaeidBayat** [comment]
I have resolved the issue by using the commit prior to Jan 26, 2019 for all libraries. Therefore, I will be closing this issue.
